language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
before_install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
install:
  - python setup.py develop
# command to run tests
script:
  - nosetests
